BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "user" (
	"id"	INTEGER DEFAULT NULL,
	"name"	MEDIUMTEXT(32) NOT NULL DEFAULT 'NULL',
	"password"	MEDIUMTEXT NOT NULL DEFAULT 'NULL',
	"verify_code"	MEDIUMTEXT NOT NULL DEFAULT 'NULL',
	"telegram"	MEDIUMTEXT NOT NULL DEFAULT 'NULL',
	"fecha_creacion" MEDIUMTEXT NOT NULL DEFAULT 'NULL',
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "schedule" (
	"id"	INTEGER DEFAULT NULL,
	"schedule_name"	TEXT,
	"schedule_info"	MEDIUMTEXT NOT NULL DEFAULT 'NULL',
	"user_id"	INTEGER DEFAULT NULL,
	"date"	DATETIME NOT NULL DEFAULT 'NULL',
	PRIMARY KEY("id"),
	FOREIGN KEY("user_id") REFERENCES "user"("id")
);
CREATE TABLE IF NOT EXISTS "event" (
	"id"	INTEGER DEFAULT NULL,
	"event_text"	TEXT,
	"date_start"	DATETIME NOT NULL DEFAULT 'NULL',
	"date_end"	DATETIME NOT NULL DEFAULT 'NULL',
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "gasto" (
	"id"	INTEGER DEFAULT NULL,
	"user_id"	INTEGER DEFAULT NULL,
	"nombre" TEXT,
	"cantidad"	REAL,
	"pagado" INTEGER DEFAULT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY("user_id") REFERENCES "user"("id")
);
COMMIT;
